[tasks.format]

    install_crate = "rustfmt"
    command = "cargo"
    args = ["fmt", "--", "--emit=files"]

[tasks.clean]
    command = "cargo"
    args = ["clean"]


[tasks.version]
    
    command = "cargo"
    args = ["version"]
    dependencies = ["clean"]

[tasks.docz]
    command = "cargo"
    args = ["doc", "--open"]
    dependenices = ["clean"]


[tasks.build]
    command = "cargo"
    args = ["build"]
    dependencies = ["clean"]


[tasks.run]
    command = "cargo"
    args = ["run"]
    dependencies = ["clean"]


    

[tasks.roombot]

   condition = { platforms =[ "windows", "linux", "mac"],channels = ["beta", "stable"]}
    
    dependencies = [
        "version",
        "docz",
        "format",
        "build",
        "run",
    ]